from flask import Flask, render_template, request, redirect, session, url_for
# babu bukatar: from cbt_take_exam import get_filtered_questions

def get_filtered_questions(all_questions, course_code):
    return [q for q in all_questions if q[0] == course_code]

questions_data = [
    # ('course_code', 'question_text', 'A', 'B', 'C', 'D', 'C', 'correct_answer')
    ('CSC101', 'What is the function of an operating system?', 'Manages software only', 'Manages hardware only', 'Manages both hardware and software', 'Only displays output', 'C', 'Manages both hardware and software'),
    ('CSC101', 'Which language is considered the foundation of computer science?', 'Python', 'C', 'Assembly', 'Pascal', 'C', 'Assembly'),
    ('CSC101', 'What does CPU stand for?', 'Central Process Unit', 'Central Processing Unit', 'Computer Processing Unit', 'Central Programming Unit', 'B', 'Central Processing Unit'),
    ('CSC101', 'What is the binary value of decimal 5?', '1010', '0010', '101', '111', 'C', '101'),
    ('CSC101', 'Which of these is an input device?', 'Monitor', 'Printer', 'Mouse', 'Speaker', 'C', 'Mouse'),
    ('CSC101', 'What is RAM used for?', 'Storing programs permanently', 'Executing applications', 'Temporary data storage', 'Backing up files', 'C', 'Temporary data storage'),
    ('CSC101', 'What is software?', 'Physical parts of a computer', 'Set of instructions for a computer', 'Electric current in the computer', 'All computer accessories', 'B', 'Set of instructions for a computer'),
    ('CSC101', 'Which of these is a programming language?', 'HTML', 'HTTP', 'SQL', 'Python', 'D', 'Python'),
    ('CSC101', 'Which generation of computers used microprocessors?', 'First', 'Second', 'Third', 'Fourth', 'D', 'Fourth'),
    ('CSC101', 'What does GUI stand for?', 'Graphical User Interface', 'General User Information', 'Global Unit Interface', 'Graphical Use Input', 'A', 'Graphical User Interface'),
]
questions_data += [
    ('CSC101', 'Which of these is a storage device?', 'Scanner', 'Hard disk', 'Monitor', 'Keyboard', 'B', 'Hard disk'),
    ('CSC101', 'Which number system do computers use?', 'Decimal', 'Octal', 'Binary', 'Hexadecimal', 'C', 'Binary'),
    ('CSC101', 'What does ALU stand for?', 'Arithmetic Logic Unit', 'Advanced Logic Unit', 'Application Logic Unit', 'Arithmetic Local Unit', 'A', 'Arithmetic Logic Unit'),
    ('CSC101', 'Which is NOT a type of computer software?', 'System software', 'Application software', 'Utility software', 'Digital software', 'D', 'Digital software'),
    ('CSC101', 'Which of these is a system software?', 'MS Word', 'Google Chrome', 'Windows OS', 'Adobe Reader', 'C', 'Windows OS'),
    ('CSC101', 'Which of these is an example of application software?', 'BIOS', 'Linux Kernel', 'MS Excel', 'Device Driver', 'C', 'MS Excel'),
    ('CSC101', 'A kilobyte (KB) equals how many bytes?', '100', '512', '1024', '2048', 'C', '1024'),
    ('CSC101', 'Which company developed the Windows operating system?', 'Apple', 'Microsoft', 'IBM', 'Google', 'B', 'Microsoft'),
    ('CSC101', 'Which one is NOT an input device?', 'Joystick', 'Keyboard', 'Monitor', 'Scanner', 'C', 'Monitor'),
    ('CSC101', 'Which of these languages is used in AI programming?', 'C++', 'FORTRAN', 'Python', 'Pascal', 'C', 'Python'),
]
questions_data += [
    ('CSC101', 'Which of these is used to connect to the internet?', 'Printer', 'Modem', 'Speaker', 'Scanner', 'B', 'Modem'),
    ('CSC101', 'What type of device is a CPU?', 'Input', 'Output', 'Storage', 'Processing', 'D', 'Processing'),
    ('CSC101', 'Which of these is volatile memory?', 'ROM', 'Hard Disk', 'RAM', 'DVD', 'C', 'RAM'),
    ('CSC101', 'What does GUI stand for?', 'Graphical User Interface', 'General User Input', 'Graphical Unified Internet', 'Global Unit Interface', 'A', 'Graphical User Interface'),
    ('CSC101', 'What is a byte made up of?', '2 bits', '4 bits', '8 bits', '16 bits', 'C', '8 bits'),
    ('CSC101', 'Which of these is NOT an operating system?', 'Linux', 'Windows', 'Oracle', 'macOS', 'C', 'Oracle'),
    ('CSC101', 'Which of these is an open-source OS?', 'Windows', 'Linux', 'MacOS', 'iOS', 'B', 'Linux'),
    ('CSC101', 'Where are programs temporarily stored during execution?', 'Hard Disk', 'RAM', 'ROM', 'Cache', 'B', 'RAM'),
    ('CSC101', 'Which part of the computer is used for long-term storage?', 'RAM', 'Cache', 'Hard Drive', 'Registers', 'C', 'Hard Drive'),
    ('CSC101', 'What does HTTP stand for?', 'HyperText Transfer Protocol', 'HyperText Translate Program', 'HighText Transport Protocol', 'Hyper Tool Transfer Process', 'A', 'HyperText Transfer Protocol'),
]
questions_data += [
    ('CSC101', 'Which programming language is used for web development?', 'Python', 'JavaScript', 'C++', 'Java', 'B', 'JavaScript'),
    ('CSC101', 'Which device is used to enter data into a computer?', 'Monitor', 'Keyboard', 'Printer', 'Speakers', 'B', 'Keyboard'),
    ('CSC101', 'Which one is an example of an input device?', 'Printer', 'Monitor', 'Scanner', 'Speakers', 'C', 'Scanner'),
    ('CSC101', 'What does HTML stand for?', 'HyperText Markup Language', 'HyperTransfer Markup Language', 'HighText Markup Language', 'HyperText Making Language', 'A', 'HyperText Markup Language'),
    ('CSC101', 'Which of the following is NOT a programming language?', 'Java', 'Python', 'HTML', 'C++', 'C', 'HTML'),
    ('CSC101', 'Which of these is used to permanently store data?', 'Cache', 'RAM', 'Hard Drive', 'CPU', 'C', 'Hard Drive'),
    ('CSC101', 'What is the purpose of an operating system?', 'To run applications', 'To manage hardware resources', 'To connect to the internet', 'To display graphics', 'B', 'To manage hardware resources'),
    ('CSC101', 'What does CPU stand for?', 'Central Program Unit', 'Central Processing Unit', 'Computer Processing Unit', 'Central Processing Unit', 'B', 'Central Processing Unit'),
    ('CSC101', 'Which of these is NOT a type of memory?', 'Cache', 'RAM', 'Flash', 'Processor', 'D', 'Processor'),
    ('CSC101', 'Which of these is a type of software?', 'Hardware', 'Operating System', 'Printer', 'Mouse', 'B', 'Operating System'),
]
questions_data = [
    ('MTH101', 'What is the derivative of sin(x)?', 'cos(x)', 'sin(x)', 'tan(x)', 'sec(x)', 'A', 'cos(x)'),
    ('MTH101', 'What is the integral of 1/x?', 'ln(x)', 'e^x', 'x^2', 'cos(x)', 'A', 'ln(x)'),
    ('MTH101', 'What is the limit of (1/x) as x approaches infinity?', '0', '1', 'infinity', 'undefined', 'A', '0'),
    ('MTH101', 'What is the second derivative of x^2?', '0', '2', '1', '4', 'B', '2'),
    ('MTH101', 'What is the integral of x^2?', 'x^3/3', 'x^3/2', 'x^4', 'x^2', 'A', 'x^3/3'),
    ('MTH101', 'The chain rule is used to differentiate functions that are:', 'Multiplying functions', 'Composing functions', 'Adding functions', 'Dividing functions', 'B', 'Composing functions'),
    ('MTH101', 'What is the derivative of e^x?', 'e^x', 'ln(x)', 'x^2', '2x', 'A', 'e^x'),
    ('MTH101', 'The fundamental theorem of calculus connects:', 'Integration and differentiation', 'Limits and derivatives', 'Addition and subtraction', 'None of the above', 'A', 'Integration and differentiation'),
    ('MTH101', 'What is the integral of sin(x)?', '-cos(x)', 'cos(x)', 'tan(x)', '-sin(x)', 'A', '-cos(x)'),
    ('MTH101', 'What is the slope of the tangent line to the curve y = x^2 at x = 2?', '4', '2', '0', '1', 'A', '4'),
    ('MTH101', 'What is the derivative of cos(x)?', 'sin(x)', '-sin(x)', 'cos(x)', '-cos(x)', 'B', '-sin(x)'),
    ('MTH101', 'Which of the following is a condition for the existence of a limit?', 'The function must be continuous', 'The function must be differentiable', 'The function must be differentiable at the point of interest', 'None of the above', 'A', 'The function must be continuous'),
    ('MTH101', 'What is the area under the curve y = x^3 from 0 to 2?', '8', '4', '6', '16', 'A', '8'),
    ('MTH101', 'What is the integral of cos(x)?', 'sin(x)', '-sin(x)', 'x^2', 'None of the above', 'A', 'sin(x)'),
    ('MTH101', 'What is the second derivative of sin(x)?', '-cos(x)', 'cos(x)', 'sin(x)', '-sin(x)', 'A', '-cos(x)'),
    ('MTH101', 'What is the derivative of tan(x)?', 'sec^2(x)', 'cos^2(x)', 'sin^2(x)', 'sec(x)', 'A', 'sec^2(x)'),
    ('MTH101', 'What is the integral of 2x?', 'x^2', 'x^3', 'x^4', '2x^2', 'A', 'x^2'),
    ('MTH101', 'Which of the following is an example of a continuous function?', 'x^2', '1/x', 'ln(x)', 'All of the above', 'A', 'x^2'),
    ('MTH101', 'What is the limit of (1/x^2) as x approaches 0?', 'Infinity', '1', '0', 'undefined', 'A', 'Infinity'),
    ('MTH101', 'What is the derivative of x^3?', '3x^2', 'x^2', '2x^3', '3x', 'A', '3x^2'),
    ('MTH101', 'What is the area under the curve y = x^2 between x = 0 and x = 1?', '1/3', '1/2', '1/4', '1', 'A', '1/3'),
    ('MTH101', 'What is the integral of 1/x^2?', '-1/x', 'ln(x)', 'x', '1/x', 'A', '-1/x'),
]
questions_data = [
    ('MTH101', 'What is the derivative of x^2 + 3x?', '2x + 3', '3x + 2', 'x^2 + 3', 'x + 3', 'A', '2x + 3'),
    ('MTH101', 'What is the integral of cos(x) from 0 to pi?', '2', '0', '1', 'pi', 'A', '2'),
    ('MTH101', 'Which of the following is an antiderivative of x^3?', 'x^4/4', 'x^4/3', 'x^5/5', 'x^2/2', 'A', 'x^4/4'),
    ('MTH101', 'What is the second derivative of x^3?', '6x', '3x^2', 'x^2', '6x^2', 'A', '6x^2'),
    ('MTH101', 'What is the limit of (sin(x))/x as x approaches 0?', '1', '0', 'infinity', 'undefined', 'A', '1'),
    ('MTH101', 'What is the integral of 2x from 0 to 1?', '1', '2', '1/2', '3', 'A', '1'),
    ('MTH101', 'What is the derivative of e^x?', 'e^x', 'ln(x)', 'x^2', 'cos(x)', 'A', 'e^x'),
    ('MTH101', 'What is the integral of 1/x from 1 to e?', '1', 'ln(e)', 'ln(1)', 'ln(e) - ln(1)', 'D', 'ln(e) - ln(1)'),
    ('MTH101', 'What is the derivative of 5x^4?', '20x^3', '4x^5', '5x^3', 'x^4', 'A', '20x^3'),
    ('MTH101', 'The derivative of ln(x) is:', '1/x', 'x', 'x^2', '1', 'A', '1/x'),
    ('MTH101', 'The area under the curve y = x^2 from 0 to 2 is:', '8/3', '2', '1', '4', 'A', '8/3'),
    ('MTH101', 'What is the integral of tan(x)?', '-ln(cos(x))', 'ln(sin(x))', 'cos(x)', 'sin(x)', 'A', '-ln(cos(x))'),
    ('MTH101', 'Which of the following is a valid limit rule?', 'Limit of sum = sum of limits', 'Limit of product = product of limits', 'Both A and B', 'None of the above', 'C', 'Both A and B'),
    ('MTH101', 'What is the limit of (cos(x) - 1)/x^2 as x approaches 0?', '0', '1', 'infinity', 'undefined', 'A', '0'),
    ('MTH101', 'What is the integral of x^3 + 2x from 0 to 1?', '2', '1.5', '1', '2.5', 'A', '2'),
    ('MTH101', 'What is the derivative of sin(x) + cos(x)?', 'cos(x) - sin(x)', '-sin(x) - cos(x)', '-cos(x) - sin(x)', 'cos(x) + sin(x)', 'A', 'cos(x) - sin(x)'),
    ('MTH101', 'What is the integral of x^2 from 1 to 2?', '7/3', '5/3', '3', '2', 'A', '7/3'),
    ('MTH101', 'What is the derivative of 3x^2 + 4x?', '6x + 4', '6x + 1', '2x + 4', '3x + 4', 'A', '6x + 4'),
    ('MTH101', 'What is the integral of e^x?', 'e^x', 'ln(x)', 'x^2', 'x', 'A', 'e^x'),
    ('MTH101', 'What is the derivative of ln(x^2)?', '2/x', '1/x^2', '2x', 'x', 'A', '2/x'),
    ('MTH101', 'What is the area under the curve y = 1/x from 1 to 2?', 'ln(2)', 'ln(1)', 'ln(2) - ln(1)', '2ln(2)', 'C', 'ln(2) - ln(1)'),
    ('MTH101', 'What is the derivative of x^5?', '5x^4', 'x^4', '4x^3', '5x', 'A', '5x^4'),
    ('MTH101', 'What is the integral of sec^2(x)?', 'tan(x)', 'cos(x)', 'sec(x)', 'sin(x)', 'A', 'tan(x)'),
    ('MTH101', 'What is the integral of sin^2(x)?', 'x/2 - sin(2x)/4', 'x/2 + sin(2x)/4', 'x - sin(2x)', 'None of the above', 'A', 'x/2 - sin(2x)/4'),
    ('MTH101', 'The chain rule is used for differentiating:', 'Composite functions', 'Multiplying functions', 'Adding functions', 'Dividing functions', 'A', 'Composite functions'),
    ('MTH101', 'What is the derivative of x^2 + 2x?', '2x + 2', '2x + 1', 'x + 2', 'x^2', 'A', '2x + 2'),
    ('MTH101', 'What is the second derivative of x^4?', '12x^2', '8x^2', '6x^3', '4x^3', 'A', '12x^2'),
    ('MTH101', 'What is the integral of sin(x) + cos(x)?', '-cos(x) + sin(x)', 'cos(x) - sin(x)', 'sin(x) + cos(x)', 'cos(x)', 'A', '-cos(x) + sin(x)'),
    ('MTH101', 'What is the derivative of 3sin(x)?', '3cos(x)', '3sin(x)', '3x^2', 'cos(x)', 'A', '3cos(x)'),
    ('MTH101', 'What is the derivative of cos(x)?', 'sin(x)', '-sin(x)', 'cos(x)', '-cos(x)', 'B', '-sin(x)'),
    ('MTH101', 'What is the limit of sin(x)/x as x approaches 0?', '1', '0', 'infinity', 'undefined', 'A', '1'),
    ('MTH101', 'The second derivative of a function gives the:', 'Concavity', 'Slope', 'Maximum', 'Minimum', 'A', 'Concavity'),
    ('MTH101', 'What is the integral of x from 0 to 3?', '9/2', '9', '3/2', 'None of the above', 'A', '9/2'),
    ('MTH101', 'What is the derivative of x^4?', '4x^3', 'x^3', '3x^4', '4x', 'A', '4x^3'),
    ('MTH101', 'What is the integral of x^5?', 'x^6/6', 'x^6/5', 'x^7/7', 'x^6/4', 'A', 'x^6/6'),
    ('MTH101', 'What is the derivative of tan(x)?', 'sec^2(x)', 'tan^2(x)', 'sec(x)', 'cos^2(x)', 'A', 'sec^2(x)'),
]
questions_data = [
    ('PHY101', 'What is the formula for calculating velocity?', 'v = s/t', 'v = t/s', 'v = 2s/t', 'v = s*t', 'A', 'v = s/t'),
    ('PHY101', 'What is the unit of force?', 'Newton', 'Joule', 'Pascal', 'Watt', 'A', 'Newton'),
    ('PHY101', 'What is the gravitational acceleration on Earth?', '9.8 m/s^2', '10 m/s^2', '9.81 m/s^2', '10.5 m/s^2', 'C', '9.81 m/s^2'),
    ('PHY101', 'What is the formula for work done?', 'W = F * d', 'W = F / d', 'W = F + d', 'W = F - d', 'A', 'W = F * d'),
    ('PHY101', 'What is the unit of energy?', 'Joule', 'Newton', 'Watt', 'Volt', 'A', 'Joule'),
    ('PHY101', 'What is the unit of power?', 'Watt', 'Joule', 'Newton', 'Ampere', 'A', 'Watt'),
    ('PHY101', 'What is the principle of conservation of energy?', 'Energy cannot be created or destroyed', 'Energy is always conserved', 'Energy can be destroyed but not created', 'Energy can be created but not destroyed', 'A', 'Energy cannot be created or destroyed'),
    ('PHY101', 'What is the formula for calculating kinetic energy?', 'KE = 1/2 mv^2', 'KE = mv^2', 'KE = 1/2 m^2v', 'KE = mv', 'A', 'KE = 1/2 mv^2'),
    ('PHY101', 'What is the speed of light in a vacuum?', '3 x 10^8 m/s', '3 x 10^6 m/s', '3 x 10^10 m/s', '3 x 10^7 m/s', 'A', '3 x 10^8 m/s'),
    ('PHY101', 'What is the formula for calculating potential energy?', 'PE = mgh', 'PE = m * v', 'PE = v^2 / 2', 'PE = F * d', 'A', 'PE = mgh'),
    ('PHY101', 'What does Ohm\'s law state?', 'V = IR', 'V = I/R', 'V = I + R', 'V = I * R', 'A', 'V = IR'),
    ('PHY101', 'What is the SI unit of current?', 'Ampere', 'Volt', 'Ohm', 'Coulomb', 'A', 'Ampere'),
    ('PHY101', 'What is the SI unit of resistance?', 'Ohm', 'Ampere', 'Volt', 'Coulomb', 'A', 'Ohm'),
    ('PHY101', 'What is the law of reflection?', 'Angle of incidence = Angle of reflection', 'Angle of incidence + Angle of reflection = 90 degrees', 'Angle of incidence = 90 degrees', 'Angle of incidence = 0 degrees', 'A', 'Angle of incidence = Angle of reflection'),
    ('PHY101', 'What is the frequency of a wave?', 'Number of oscillations per second', 'Speed of wave', 'Wavelength', 'Amplitude', 'A', 'Number of oscillations per second'),
    ('PHY101', 'What is the formula for calculating the period of a wave?', 'T = 1/f', 'T = f / 1', 'T = f', 'T = f^2', 'A', 'T = 1/f'),
    ('PHY101', 'What is the unit of frequency?', 'Hertz', 'Watt', 'Newton', 'Joule', 'A', 'Hertz'),
    ('PHY101', 'What is the speed of sound in air?', '343 m/s', '300 m/s', '340 m/s', '400 m/s', 'A', '343 m/s'),
    ('PHY101', 'What is the SI unit of temperature?', 'Kelvin', 'Celsius', 'Fahrenheit', 'Rankine', 'A', 'Kelvin'),
    ('PHY101', 'What is the formula for calculating force?', 'F = ma', 'F = mv', 'F = m/v', 'F = m^2a', 'A', 'F = ma'),
    ('PHY101', 'What is the principle of buoyancy?', 'An object immersed in a fluid experiences an upward force', 'An object sinks when it displaces more fluid', 'An object will float if its weight is more than the fluid displaced', 'None of the above', 'A', 'An object immersed in a fluid experiences an upward force'),
    ('PHY101', 'What is the energy stored in a spring called?', 'Elastic potential energy', 'Kinetic energy', 'Gravitational potential energy', 'Mechanical energy', 'A', 'Elastic potential energy'),
    ('PHY101', 'What is the formula for calculating pressure?', 'P = F / A', 'P = A / F', 'P = F * A', 'P = A * F', 'A', 'P = F / A'),
    ('PHY101', 'What is the unit of pressure?', 'Pascal', 'Newton', 'Joule', 'Watt', 'A', 'Pascal'),
    ('PHY101', 'What is the Doppler effect?', 'Change in frequency due to motion', 'Change in wavelength due to motion', 'Change in speed due to motion', 'Change in amplitude due to motion', 'A', 'Change in frequency due to motion'),
    ('PHY101', 'What is the formula for the acceleration of an object?', 'a = (v - u) / t', 'a = v * u * t', 'a = v + u / t', 'a = u / t', 'A', 'a = (v - u) / t'),
    ('PHY101', 'What is the principle of conservation of momentum?', 'Momentum before collision = Momentum after collision', 'Momentum before collision > Momentum after collision', 'Momentum before collision < Momentum after collision', 'Momentum is always zero', 'A', 'Momentum before collision = Momentum after collision'),
    ('PHY101', 'What is the formula for gravitational force between two objects?', 'F = G(m1m2) / r^2', 'F = G(m1m2) * r^2', 'F = G(m1 + m2) / r^2', 'F = G(m1 + m2) * r^2', 'A', 'F = G(m1m2) / r^2'),
    ('PHY101', 'What is the concept of inertial mass?', 'An object\'s resistance to changes in motion', 'An object\'s weight in a gravitational field', 'An object\'s volume', 'An object\'s density', 'A', 'An object\'s resistance to changes in motion'),
    ('PHY101', 'What is the energy required to change the temperature of a substance?', 'Heat', 'Work', 'Power', 'Energy', 'A', 'Heat'),
    ('PHY101', 'What is the law of universal gravitation?', 'Every object attracts every other object with a force proportional to their masses and inversely proportional to the square of the distance between them', 'Every object attracts every other object with a force proportional to their volume', 'Every object repels every other object with a force proportional to their masses', 'None of the above', 'A', 'Every object attracts every other object with a force proportional to their masses and inversely proportional to the square of the distance between them'),
    ('PHY101', 'What is the wavelength of a wave?', 'Distance between two consecutive crests or troughs', 'Distance between the wave\'s source and observer', 'Distance the wave travels per second', 'Distance between any two points on the wave', 'A', 'Distance between two consecutive crests or troughs'),
    ('PHY101', 'What is the formula for calculating the velocity of a wave?', 'v = f * λ', 'v = λ / f', 'v = f / λ', 'v = λ * f', 'A', 'v = f * λ'),
    ('PHY101', 'What is the formula for calculating impulse?', 'Impulse = F * t', 'Impulse = F / t', 'Impulse = m * v', 'Impulse = m * a', 'A', 'Impulse = F * t'),
    ('PHY101', 'What is the effect of a balanced force on an object?', 'No motion or constant velocity', 'Increase in speed', 'Increase in acceleration', 'Decrease in speed', 'A', 'No motion or constant velocity'),
    ('PHY101', 'What is the total mechanical energy of an object?', 'Sum of kinetic energy and potential energy', 'Kinetic energy only', 'Potential energy only', 'None of the above', 'A', 'Sum of kinetic energy and potential energy'),
    ('PHY101', 'What is the force required to move an object at constant speed on a horizontal surface?', 'Equal to the frictional force', 'Greater than the frictional force', 'Less than the frictional force', 'Zero', 'A', 'Equal to the frictional force'),
    ('PHY101', 'What is the law of conservation of angular momentum?', 'The total angular momentum of a system remains constant if no external torque acts on it', 'The angular momentum is always zero', 'The angular momentum of a rotating object is always proportional to its velocity', 'None of the above', 'A', 'The total angular momentum of a system remains constant if no external torque acts on it'),
]
questions_data = [
    ('CHM101', 'What is the chemical symbol for water?', 'H2O', 'O2', 'CO2', 'H2', 'A', 'H2O'),
    ('CHM101', 'What is the atomic number of carbon?', '6', '12', '8', '14', 'A', '6'),
    ('CHM101', 'Which of the following is an alkaline earth metal?', 'Calcium', 'Sodium', 'Iron', 'Copper', 'A', 'Calcium'),
    ('CHM101', 'What is the molecular formula for methane?', 'CH4', 'C2H6', 'C3H8', 'C4H10', 'A', 'CH4'),
    ('CHM101', 'Which of the following is a noble gas?', 'Helium', 'Oxygen', 'Nitrogen', 'Hydrogen', 'A', 'Helium'),
    ('CHM101', 'What is the pH value of a neutral solution?', '7', '0', '14', '3', 'A', '7'),
    ('CHM101', 'Which element is a halogen?', 'Chlorine', 'Oxygen', 'Nitrogen', 'Carbon', 'A', 'Chlorine'),
    ('CHM101', 'What is the chemical formula for hydrochloric acid?', 'HCl', 'H2SO4', 'NaOH', 'HNO3', 'A', 'HCl'),
    ('CHM101', 'What is the atomic number of oxygen?', '8', '16', '14', '10', 'A', '8'),
    ('CHM101', 'What is the name of the compound NaCl?', 'Sodium chloride', 'Sodium sulfate', 'Sodium hydroxide', 'Sodium nitrate', 'A', 'Sodium chloride'),
    ('CHM101', 'Which of the following is a strong acid?', 'HCl', 'CH3COOH', 'H2CO3', 'NH3', 'A', 'HCl'),
    ('CHM101', 'Which element is essential for the formation of bones in the human body?', 'Calcium', 'Phosphorus', 'Magnesium', 'Iron', 'A', 'Calcium'),
    ('CHM101', 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Cu', 'Pb', 'A', 'Au'),
    ('CHM101', 'What is the molecular formula for ammonia?', 'NH3', 'N2H4', 'NH2', 'N2H3', 'A', 'NH3'),
    ('CHM101', 'Which of the following is an example of an ionic bond?', 'NaCl', 'H2O', 'CO2', 'O2', 'A', 'NaCl'),
    ('CHM101', 'What is the process of a solid turning into a liquid called?', 'Melting', 'Freezing', 'Condensation', 'Evaporation', 'A', 'Melting'),
    ('CHM101', 'What is the element with the highest atomic number?', 'Oganesson', 'Uranium', 'Plutonium', 'Neptunium', 'A', 'Oganesson'),
    ('CHM101', 'Which gas is most commonly used in light bulbs?', 'Argon', 'Oxygen', 'Nitrogen', 'Hydrogen', 'A', 'Argon'),
    ('CHM101', 'Which of the following is a non-metal?', 'Sulfur', 'Iron', 'Magnesium', 'Calcium', 'A', 'Sulfur'),
    ('CHM101', 'What is the molar mass of water (H2O)?', '18 g/mol', '20 g/mol', '16 g/mol', '22 g/mol', 'A', '18 g/mol'),
    ('CHM101', 'What type of bond is formed between two hydrogen atoms in H2?', 'Covalent bond', 'Ionic bond', 'Metallic bond', 'Hydrogen bond', 'A', 'Covalent bond'),
    ('CHM101', 'What is the chemical symbol for sodium?', 'Na', 'K', 'Ca', 'Mg', 'A', 'Na'),
    ('CHM101', 'Which of the following is a liquid at room temperature?', 'Water', 'Oxygen', 'Helium', 'Nitrogen', 'A', 'Water'),
    ('CHM101', 'Which of the following elements is a metalloid?', 'Silicon', 'Sulfur', 'Oxygen', 'Iron', 'A', 'Silicon'),
    ('CHM101', 'Which of the following is a strong base?', 'NaOH', 'HCl', 'H2SO4', 'CH3COOH', 'A', 'NaOH'),
    ('CHM101', 'What is the unit of concentration in chemistry?', 'Molarity', 'Density', 'Mass', 'Volume', 'A', 'Molarity'),
    ('CHM101', 'What is the common name for dihydrogen monoxide?', 'Water', 'Hydrogen peroxide', 'Ammonia', 'Methane', 'A', 'Water'),
    ('CHM101', 'Which of the following is a property of acids?', 'Sour taste', 'Bitter taste', 'Slippery', 'None of the above', 'A', 'Sour taste'),
    ('CHM101', 'What is the atomic number of hydrogen?', '1', '2', '3', '0', 'A', '1'),
    ('CHM101', 'Which of the following elements is most reactive?', 'Francium', 'Helium', 'Oxygen', 'Neon', 'A', 'Francium'),
    ('CHM101', 'What is the name of the acid found in stomachs?', 'Hydrochloric acid', 'Sulfuric acid', 'Acetic acid', 'Citric acid', 'A', 'Hydrochloric acid'),
    ('CHM101', 'What is the formula for calcium chloride?', 'CaCl2', 'NaCl', 'MgCl2', 'KCl', 'A', 'CaCl2'),
    ('CHM101', 'Which element has the highest electronegativity?', 'Fluorine', 'Oxygen', 'Chlorine', 'Nitrogen', 'A', 'Fluorine'),
    ('CHM101', 'What is the color of copper sulfate crystals?', 'Blue', 'Green', 'Red', 'Yellow', 'A', 'Blue'),
    ('CHM101', 'What is the chemical formula for methane?', 'CH4', 'C2H6', 'C3H8', 'C4H10', 'A', 'CH4'),
    ('CHM101', 'Which of the following is a common oxidation state of iron?', 'Fe2+', 'Fe3+', 'Fe1+', 'Fe4+', 'A', 'Fe2+'),
    ('CHM101', 'What is the atomic mass of carbon?', '12.01 u', '14.01 u', '16.00 u', '18.01 u', 'A', '12.01 u'),
    ('CHM101', 'Which of the following is a characteristic of an exothermic reaction?', 'Releases energy', 'Absorbs energy', 'Does not involve energy', 'All of the above', 'A', 'Releases energy'),
    ('CHM101', 'Which gas is produced when an acid reacts with a metal?', 'Hydrogen', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'A', 'Hydrogen'),
    ('CHM101', 'What is the process of a gas turning into a liquid called?', 'Condensation', 'Evaporation', 'Melting', 'Sublimation', 'A', 'Condensation'),
    ('CHM101', 'Which of the following is an example of a saturated hydrocarbon?', 'Methane', 'Ethene', 'Ethene', 'Acetylene', 'A', 'Methane'),
]
questions_data = [
    ('BIO101', 'What is the basic unit of life?', 'Cell', 'Atom', 'Molecule', 'Organ', 'A', 'Cell'),
    ('BIO101', 'What is the process by which plants make their food?', 'Photosynthesis', 'Respiration', 'Fermentation', 'Digestion', 'A', 'Photosynthesis'),
    ('BIO101', 'Which organ in the human body is responsible for pumping blood?', 'Heart', 'Lungs', 'Liver', 'Kidneys', 'A', 'Heart'),
    ('BIO101', 'What is the genetic material in humans?', 'DNA', 'RNA', 'Protein', 'Carbohydrate', 'A', 'DNA'),
    ('BIO101', 'Which of the following is a component of the cell membrane?', 'Phospholipids', 'Proteins', 'Carbohydrates', 'All of the above', 'D', 'All of the above'),
    ('BIO101', 'Which organelle is known as the powerhouse of the cell?', 'Mitochondria', 'Nucleus', 'Ribosome', 'Endoplasmic reticulum', 'A', 'Mitochondria'),
    ('BIO101', 'What is the process of cell division that produces two identical daughter cells?', 'Mitosis', 'Meiosis', 'Fission', 'Fusion', 'A', 'Mitosis'),
    ('BIO101', 'What type of bond is formed between two water molecules?', 'Hydrogen bond', 'Ionic bond', 'Covalent bond', 'Metallic bond', 'A', 'Hydrogen bond'),
    ('BIO101', 'What is the function of ribosomes in a cell?', 'Protein synthesis', 'Energy production', 'DNA replication', 'Waste elimination', 'A', 'Protein synthesis'),
    ('BIO101', 'Which of the following is NOT a characteristic of living organisms?', 'Ability to reproduce', 'Ability to grow', 'Ability to perform photosynthesis', 'Ability to move', 'C', 'Ability to perform photosynthesis'),
    ('BIO101', 'Which part of the cell controls cell activities and contains genetic material?', 'Nucleus', 'Cytoplasm', 'Cell membrane', 'Mitochondria', 'A', 'Nucleus'),
    ('BIO101', 'What is the chemical formula for glucose?', 'C6H12O6', 'C6H6O6', 'C2H5OH', 'CH4', 'A', 'C6H12O6'),
    ('BIO101', 'Which of the following is an example of a prokaryotic cell?', 'Bacteria', 'Fungus', 'Plant', 'Animal', 'A', 'Bacteria'),
    ('BIO101', 'Which molecule carries genetic information in the form of a double helix?', 'DNA', 'RNA', 'Protein', 'Carbohydrates', 'A', 'DNA'),
    ('BIO101', 'What is the process by which cells obtain energy from food?', 'Cellular respiration', 'Photosynthesis', 'Fermentation', 'Transpiration', 'A', 'Cellular respiration'),
    ('BIO101', 'Which of the following is a type of asexual reproduction?', 'Binary fission', 'Sexual reproduction', 'Meiosis', 'Fertilization', 'A', 'Binary fission'),
    ('BIO101', 'What is the function of chlorophyll in plants?', 'Absorbs light energy', 'Stores water', 'Transports nutrients', 'Synthesizes food', 'A', 'Absorbs light energy'),
    ('BIO101', 'Which of the following is NOT a part of the circulatory system?', 'Stomach', 'Heart', 'Blood vessels', 'Blood', 'A', 'Stomach'),
    ('BIO101', 'What is the process of converting light energy into chemical energy in plants?', 'Photosynthesis', 'Respiration', 'Digestion', 'Fermentation', 'A', 'Photosynthesis'),
    ('BIO101', 'Which organ in the human body is responsible for filtering waste from the blood?', 'Kidneys', 'Liver', 'Heart', 'Lungs', 'A', 'Kidneys'),
    ('BIO101', 'Which type of cell division produces gametes?', 'Meiosis', 'Mitosis', 'Fission', 'Maturation', 'A', 'Meiosis'),
    ('BIO101', 'What is the role of the mitochondria?', 'Produce energy (ATP)', 'Protein synthesis', 'Transport materials', 'Storage of genetic material', 'A', 'Produce energy (ATP)'),
    ('BIO101', 'Which of the following is the basic unit of heredity?', 'Gene', 'Chromosome', 'Cell', 'Protein', 'A', 'Gene'),
    ('BIO101', 'What is the process of converting RNA into a protein?', 'Translation', 'Transcription', 'Replication', 'Excretion', 'A', 'Translation'),
    ('BIO101', 'What is the name of the process by which water moves across a semipermeable membrane?', 'Osmosis', 'Diffusion', 'Active transport', 'Facilitated diffusion', 'A', 'Osmosis'),
    ('BIO101', 'What is the function of white blood cells?', 'Fight infections', 'Carry oxygen', 'Carry nutrients', 'Provide energy', 'A', 'Fight infections'),
    ('BIO101', 'Which organelle is involved in protein synthesis?', 'Ribosomes', 'Nucleus', 'Mitochondria', 'Golgi apparatus', 'A', 'Ribosomes'),
    ('BIO101', 'What type of molecule is an enzyme?', 'Protein', 'Carbohydrate', 'Lipid', 'Nucleic acid', 'A', 'Protein'),
    ('BIO101', 'Which of the following is a component of the immune system?', 'White blood cells', 'Red blood cells', 'Platelets', 'All of the above', 'A', 'White blood cells'),
    ('BIO101', 'What is the function of the cell membrane?', 'Regulate what enters and exits the cell', 'Provide support and shape', 'Carry out chemical reactions', 'Store genetic information', 'A', 'Regulate what enters and exits the cell'),
    ('BIO101', 'What is the name of the structure that stores food and water in a plant cell?', 'Vacuole', 'Chloroplast', 'Ribosome', 'Mitochondrion', 'A', 'Vacuole'),
    ('BIO101', 'Which type of genetic material is found in the nucleus?', 'DNA', 'RNA', 'Protein', 'Enzyme', 'A', 'DNA'),
    ('BIO101', 'What is the main function of red blood cells?', 'Carry oxygen', 'Fight infection', 'Transport nutrients', 'Digest food', 'A', 'Carry oxygen'),
    ('BIO101', 'Which of the following structures are involved in photosynthesis?', 'Chloroplasts', 'Mitochondria', 'Nucleus', 'Lysosomes', 'A', 'Chloroplasts'),
    ('BIO101', 'Which of the following is true about plant cells?', 'They contain chloroplasts', 'They have a cell membrane', 'They have a cell wall', 'All of the above', 'D', 'All of the above'),
    ('BIO101', 'What are the building blocks of proteins?', 'Amino acids', 'Fatty acids', 'Monosaccharides', 'Nucleotides', 'A', 'Amino acids'),
    ('BIO101', 'What is the process by which DNA is copied to RNA?', 'Transcription', 'Replication', 'Translation', 'Mutation', 'A', 'Transcription'),
    ('BIO101', 'Which of the following structures is present in plant cells but not animal cells?', 'Chloroplasts', 'Mitochondria', 'Nucleus', 'Ribosomes', 'A', 'Chloroplasts'),
    ('BIO101', 'What is the function of the Golgi apparatus?', 'Modify, sort, and package proteins', 'Synthesize proteins', 'Store genetic information', 'Transport materials', 'A', 'Modify, sort, and package proteins'),
    ('BIO101', 'What is the process of converting food into energy in the presence of oxygen called?', 'Aerobic respiration', 'Fermentation', 'Anaerobic respiration', 'Photosynthesis', 'A', 'Aerobic respiration'),
    ('BIO101', 'Which of the following is an example of a lipid?', 'Fat', 'Protein', 'Carbohydrate', 'Nucleic acid', 'A', 'Fat'),
    ('BIO101', 'What is the function of the cytoplasm?', 'Support and protect the cell', 'Store nutrients', 'Carry out chemical reactions', 'Transport materials', 'A', 'Support and protect the cell')
]
questions_data = [
    ('GST101', 'What is the main purpose of education?', 'To learn to read and write', 'To develop critical thinking skills', 'To get a job', 'To socialize with peers', 'B', 'To develop critical thinking skills'),
    ('GST101', 'Which of the following is a key aspect of time management?', 'Prioritizing tasks', 'Watching TV', 'Chatting with friends', 'Sleeping for long hours', 'A', 'Prioritizing tasks'),
    ('GST101', 'What is a goal?', 'A dream', 'A plan with action steps', 'A wish', 'An idea', 'B', 'A plan with action steps'),
    ('GST101', 'What is critical thinking?', 'Accepting information as it is', 'Thinking carefully about information before making decisions', 'Memorizing facts', 'Ignoring information', 'B', 'Thinking carefully about information before making decisions'),
    ('GST101', 'What is the best way to avoid procrastination?', 'Breaking tasks into smaller parts', 'Waiting for the right time', 'Ignoring tasks', 'Multitasking', 'A', 'Breaking tasks into smaller parts'),
    ('GST101', 'Which of the following is a study technique that helps retain information?', 'Active reading', 'Rereading the text passively', 'Watching videos without taking notes', 'Listening to music while studying', 'A', 'Active reading'),
    ('GST101', 'What is a SMART goal?', 'A goal that is specific, measurable, achievable, relevant, and time-bound', 'A goal that is flexible and non-specific', 'A goal that is related to personal desires', 'A goal that does not require effort', 'A', 'A goal that is specific, measurable, achievable, relevant, and time-bound'),
    ('GST101', 'What is a major benefit of studying in groups?', 'Exposure to different perspectives', 'More time to socialize', 'No need to study alone', 'No benefit', 'A', 'Exposure to different perspectives'),
    ('GST101', 'What does SWOT stand for?', 'Strengths, Weaknesses, Opportunities, Threats', 'Special, Weak, Outstanding, Timeless', 'Skills, Wisdom, Outcomes, Time', 'Systematic, Workable, Organizational, Tactical', 'A', 'Strengths, Weaknesses, Opportunities, Threats'),
    ('GST101', 'What does the term “self-discipline” refer to?', 'Being able to control oneself and stay focused on tasks', 'Being able to follow others', 'Having the ability to make others follow you', 'Being able to work without breaks', 'A', 'Being able to control oneself and stay focused on tasks'),
    ('GST101', 'Which of the following is NOT a time-wasting activity?', 'Prioritizing tasks', 'Watching TV for long periods', 'Procrastination', 'Spending time on social media excessively', 'A', 'Prioritizing tasks'),
    ('GST101', 'What does it mean to be “goal-oriented”?', 'Focusing on achieving specific objectives', 'Changing goals frequently', 'Avoiding setting goals', 'Focusing on entertainment', 'A', 'Focusing on achieving specific objectives'),
    ('GST101', 'Which is an example of a positive habit?', 'Studying every day at the same time', 'Skipping classes to relax', 'Sleeping late every night', 'Using mobile phone during study sessions', 'A', 'Studying every day at the same time'),
    ('GST101', 'Which of the following is an effective method of note-taking?', 'Summarizing key points', 'Writing everything down word for word', 'Ignoring difficult topics', 'Writing notes in a random order', 'A', 'Summarizing key points'),
    ('GST101', 'What is an important characteristic of an effective leader?', 'The ability to inspire and motivate others', 'The ability to be rude', 'The ability to control people', 'The ability to delegate all tasks to others', 'A', 'The ability to inspire and motivate others'),
    ('GST101', 'What is the primary purpose of networking?', 'Building professional relationships', 'Making friends', 'Having fun', 'Having conversations with family members', 'A', 'Building professional relationships'),
    ('GST101', 'What is the main benefit of attending workshops and seminars?', 'Learning new skills and knowledge', 'Free food', 'Meeting friends', 'No benefit', 'A', 'Learning new skills and knowledge'),
    ('GST101', 'What does “emotional intelligence” mean?', 'Understanding and managing emotions', 'Being able to hide emotions', 'Being emotionally numb', 'Not caring about others\' emotions', 'A', 'Understanding and managing emotions'),
    ('GST101', 'What is the significance of communication skills?', 'Helps in expressing thoughts clearly', 'Helps in avoiding conversation', 'Helps in isolating oneself', 'Helps in staying quiet', 'A', 'Helps in expressing thoughts clearly'),
    ('GST101', 'What does it mean to be “organized”?', 'Having a system to manage tasks and resources', 'Having things scattered everywhere', 'Having random piles of materials', 'Being disorganized', 'A', 'Having a system to manage tasks and resources'),
    ('GST101', 'Why is decision-making important?', 'Helps in achieving personal and professional goals', 'It is not important', 'To avoid thinking', 'To please others', 'A', 'Helps in achieving personal and professional goals'),
    ('GST101', 'What is a “growth mindset”?', 'Belief that abilities can be developed with effort and learning', 'Belief that abilities are fixed and cannot change', 'Belief that learning is not necessary', 'Belief that others should do everything', 'A', 'Belief that abilities can be developed with effort and learning'),
    ('GST101', 'What is the purpose of setting priorities?', 'To focus on important tasks first', 'To waste time on less important tasks', 'To avoid responsibility', 'To ignore deadlines', 'A', 'To focus on important tasks first'),
    ('GST101', 'What is “conflict resolution”?', 'Finding a way to resolve differences in opinions or actions', 'Ignoring the conflict', 'Escalating the conflict', 'Avoiding the conflict', 'A', 'Finding a way to resolve differences in opinions or actions'),
    ('GST101', 'What does it mean to “delegate” a task?', 'To assign the task to someone else', 'To do everything yourself', 'To ignore the task', 'To pass the task to a superior', 'A', 'To assign the task to someone else'),
    ('GST101', 'Which of the following is a sign of procrastination?', 'Putting off tasks until the last minute', 'Focusing on tasks immediately', 'Planning ahead', 'Organizing tasks in advance', 'A', 'Putting off tasks until the last minute'),
    ('GST101', 'What is the importance of teamwork?', 'Combining skills and knowledge to achieve common goals', 'Doing everything alone', 'Avoiding interaction with others', 'Competing with others', 'A', 'Combining skills and knowledge to achieve common goals'),
    ('GST101', 'Which of the following is a key element of effective time management?', 'Setting clear goals and deadlines', 'Waiting for inspiration', 'Procrastination', 'Ignoring tasks', 'A', 'Setting clear goals and deadlines'),
    ('GST101', 'What is the main reason for setting SMART goals?', 'To make goals clear, achievable, and time-bound', 'To have vague goals', 'To set unrealistic goals', 'To avoid goal setting', 'A', 'To make goals clear, achievable, and time-bound'),
    ('GST101', 'Which of the following is a recommended method for managing stress?', 'Physical exercise', 'Avoiding all responsibilities', 'Ignoring problems', 'Staying isolated', 'A', 'Physical exercise'),
    ('GST101', 'What is self-awareness?', 'Knowing your strengths and weaknesses', 'Ignoring your emotions', 'Pretending to be someone else', 'Ignoring feedback', 'A', 'Knowing your strengths and weaknesses'),
    ('GST101', 'What does “empathy” mean?', 'Understanding and sharing the feelings of others', 'Ignoring others’ feelings', 'Only caring about your own feelings', 'Being indifferent', 'A', 'Understanding and sharing the feelings of others'),
    ('GST101', 'What is the role of feedback in personal development?', 'Helps to identify areas for improvement', 'Makes you feel bad', 'Has no importance', 'Keeps you from learning', 'A', 'Helps to identify areas for improvement'),
    ('GST101', 'What is the definition of success?', 'Achieving personal and professional goals', 'Having lots of money', 'Being famous', 'Having a comfortable life', 'A', 'Achieving personal and professional goals'),
    ('GST101', 'Which of the following is a key part of effective problem-solving?', 'Analyzing the problem and identifying possible solutions', 'Avoiding the problem', 'Ignoring the problem', 'Blaming others', 'A', 'Analyzing the problem and identifying possible solutions'),
    ('GST101', 'What is the importance of learning from mistakes?', 'Helps to grow and improve', 'Makes you feel embarrassed', 'Has no impact', 'Is not necessary', 'A', 'Helps to grow and improve'),
    ('GST101', 'What is one of the most important aspects of professional development?', 'Continuous learning and growth', 'Staying in the same position', 'Avoiding challenges', 'Ignoring feedback', 'A', 'Continuous learning and growth')
]
questions_data = [
    ('STA101', 'What is statistics?', 'The study of human behavior', 'The study of data collection, analysis, and interpretation', 'The study of economics', 'The study of history', 'B', 'The study of data collection, analysis, and interpretation'),
    ('STA101', 'Which of the following is a type of data?', 'Qualitative data', 'Exponential data', 'Fibonacci data', 'Imaginary data', 'A', 'Qualitative data'),
    ('STA101', 'What is the mean of a data set?', 'The most frequent value', 'The middle value', 'The average of all the values', 'The range of values', 'C', 'The average of all the values'),
    ('STA101', 'What is the median of a data set?', 'The most frequent value', 'The middle value when data is arranged in order', 'The average of all values', 'The highest value', 'B', 'The middle value when data is arranged in order'),
    ('STA101', 'What is the mode of a data set?', 'The average value', 'The highest value', 'The most frequent value', 'The middle value', 'C', 'The most frequent value'),
    ('STA101', 'What is a normal distribution?', 'A distribution with two peaks', 'A symmetric bell-shaped curve', 'A distribution with one peak', 'A distribution with multiple peaks', 'B', 'A symmetric bell-shaped curve'),
    ('STA101', 'What does variance measure in a data set?', 'The spread of data around the mean', 'The average value of the data', 'The frequency of data', 'The middle value of the data', 'A', 'The spread of data around the mean'),
    ('STA101', 'What is the standard deviation?', 'The square of variance', 'The mean value of data', 'The most frequent value', 'The difference between the highest and lowest values', 'A', 'The square of variance'),
    ('STA101', 'What is a sample in statistics?', 'A subset of a population used for analysis', 'The entire population', 'A random selection from a population', 'The median value of data', 'A', 'A subset of a population used for analysis'),
    ('STA101', 'What is a population in statistics?', 'A sample group from a larger population', 'The entire group being studied', 'A random selection of data', 'A selected group of individuals', 'B', 'The entire group being studied'),
    ('STA101', 'What is a hypothesis in statistics?', 'A conclusion based on data', 'A statement or assumption that can be tested', 'A descriptive summary of data', 'An outcome of an experiment', 'B', 'A statement or assumption that can be tested'),
    ('STA101', 'What is a confidence interval?', 'A range of values used to estimate a population parameter', 'A method of calculating the mean', 'A set of values with no specific range', 'The middle value of data', 'A', 'A range of values used to estimate a population parameter'),
    ('STA101', 'What is a correlation coefficient?', 'A value indicating the relationship between two variables', 'The mean of two variables', 'The standard deviation of two variables', 'The average of a sample group', 'A', 'A value indicating the relationship between two variables'),
    ('STA101', 'What is a regression analysis?', 'A method to predict the value of one variable based on another', 'A method of calculating variance', 'A method to find the mode of data', 'A method to calculate the mean of data', 'A', 'A method to predict the value of one variable based on another'),
    ('STA101', 'What is a P-value?', 'The probability that the results are due to random chance', 'The mean of the data', 'The standard deviation of the data', 'The mode of the data', 'A', 'The probability that the results are due to random chance'),
    ('STA101', 'What is a null hypothesis?', 'A statement that there is no effect or relationship', 'A statement that there is a relationship', 'A test for mean differences', 'A test for data validity', 'A', 'A statement that there is no effect or relationship'),
    ('STA101', 'What is an alternative hypothesis?', 'A statement that contradicts the null hypothesis', 'A statement that supports the null hypothesis', 'A statement that is unrelated to the null hypothesis', 'A hypothesis based on assumptions', 'A', 'A statement that contradicts the null hypothesis'),
    ('STA101', 'What does a type I error refer to in hypothesis testing?', 'Rejecting a true null hypothesis', 'Accepting a false null hypothesis', 'Rejecting a false null hypothesis', 'Accepting a true null hypothesis', 'A', 'Rejecting a true null hypothesis'),
    ('STA101', 'What is a type II error?', 'Failing to reject a false null hypothesis', 'Rejecting a true null hypothesis', 'Accepting a true null hypothesis', 'Failing to accept a true null hypothesis', 'A', 'Failing to reject a false null hypothesis'),
    ('STA101', 'What is an outlier?', 'A value significantly different from the rest of the data', 'The most frequent value', 'The middle value of data', 'The highest value', 'A', 'A value significantly different from the rest of the data'),
    ('STA101', 'What is a box plot used for?', 'To visualize the distribution of data', 'To calculate the mean', 'To show the relationship between two variables', 'To find the standard deviation', 'A', 'To visualize the distribution of data'),
    ('STA101', 'What is the chi-square test used for?', 'Testing the association between two categorical variables', 'Testing the mean of a sample', 'Testing the relationship between two continuous variables', 'Testing the variance of a population', 'A', 'Testing the association between two categorical variables'),
    ('STA101', 'What is the purpose of statistical inference?', 'To make conclusions about a population based on a sample', 'To calculate the mean of a data set', 'To calculate the mode', 'To calculate the frequency of data', 'A', 'To make conclusions about a population based on a sample'),
    ('STA101', 'What is the difference between descriptive and inferential statistics?', 'Descriptive statistics summarize data, inferential statistics make predictions based on data', 'Descriptive statistics are used for experiments, inferential statistics are for surveys', 'Descriptive statistics are for qualitative data, inferential statistics are for quantitative data', 'There is no difference between them', 'A', 'Descriptive statistics summarize data, inferential statistics make predictions based on data'),
    ('STA101', 'What is a sampling distribution?', 'A distribution of sample statistics obtained from repeated sampling', 'A distribution of population data', 'A distribution of observed values', 'A distribution of continuous variables', 'A', 'A distribution of sample statistics obtained from repeated sampling'),
    ('STA101', 'What is the central limit theorem?', 'The distribution of the sample means approaches a normal distribution as sample size increases', 'The distribution of individual data points approaches normality', 'The sample mean will always be equal to the population mean', 'The sample size will always be small', 'A', 'The distribution of the sample means approaches a normal distribution as sample size increases'),
    ('STA101', 'What is the purpose of hypothesis testing?', 'To assess whether a hypothesis about a population parameter is supported by sample data', 'To calculate the mean of data', 'To determine the median of a data set', 'To find the mode of the data', 'A', 'To assess whether a hypothesis about a population parameter is supported by sample data'),
    ('STA101', 'What does a two-tailed test in hypothesis testing indicate?', 'That the effect could be in either direction', 'That the effect is only in one direction', 'That the sample size is too large', 'That there is no effect', 'A', 'That the effect could be in either direction'),
    ('STA101', 'What is the relationship between population and sample in statistics?', 'A sample is a subset of a population', 'A sample is a random selection from a population', 'A sample is a summary of the entire population', 'A sample is an entire population', 'A', 'A sample is a subset of a population'),
    ('STA101', 'What is the difference between a parameter and a statistic?', 'A parameter describes a population, a statistic describes a sample', 'A parameter describes a sample, a statistic describes a population', 'They are the same', 'A parameter is a hypothesis, a statistic is a test', 'A', 'A parameter describes a population, a statistic describes a sample'),
    ('STA101', 'What is the coefficient of determination?', 'The proportion of variance in the dependent variable explained by the independent variable', 'The proportion of variance in the independent variable explained by the dependent variable', 'The proportion of data explained by outliers', 'The proportion of variance explained by the mode', 'A', 'The proportion of variance in the dependent variable explained by the independent variable'),
    ('STA101', 'What is an experiment in statistics?', 'A controlled study to observe the effect of a variable on another variable', 'A survey to gather information', 'A study of historical data', 'A collection of data points from the population', 'A', 'A controlled study to observe the effect of a variable on another variable'),
    ('STA101', 'What is an observation in statistics?', 'A single data point or measurement', 'The average of all data points', 'The range of data values', 'A hypothetical value in an experiment', 'A', 'A single data point or measurement'),
    ('STA101', 'What is the purpose of sampling in statistics?', 'To select a representative group from a population for analysis', 'To collect data from the entire population', 'To eliminate outliers from the', 'A Abubakar suleman'),
]
questions_data = [
    ('MATH201', 'What is the derivative of x^2?', '2x', 'x^2', '2x^3', 'x', 'A', '2x'),
    ('MATH201', 'What is the integral of x?', 'x^2/2', 'x^2', '2x', 'x', 'A', 'x^2/2'),
    ('MATH201', 'What is the limit of 1/x as x approaches infinity?', '0', '1', 'Infinity', 'Undefined', 'A', '0'),
    ('MATH201', 'What is the product rule in calculus?', 'd/dx(fg) = fg’', 'd/dx(fg) = f’g + fg’', 'd/dx(fg) = f’g’,', 'd/dx(fg) = fg + f’g’', 'B', 'd/dx(fg) = f’g + fg’'),
    ('MATH201', 'What is the chain rule in calculus?', 'd/dx(f(g(x))) = f’(g(x)) * g’(x)', 'd/dx(f(g(x))) = f’(x) * g(x)', 'd/dx(f(g(x))) = f(g(x)) * g’(x)', 'None of the above', 'A', 'd/dx(f(g(x))) = f’(g(x)) * g’(x)'),
    ('MATH201', 'What is the fundamental theorem of calculus?', 'The derivative of an integral is the original function', 'The integral of a derivative is the original function', 'The limit of an integral is the original function', 'None of the above', 'A', 'The derivative of an integral is the original function'),
    ('MATH201', 'What is the derivative of sin(x)?', 'cos(x)', '-cos(x)', 'sin(x)', '-sin(x)', 'A', 'cos(x)'),
    ('MATH201', 'What is the integral of cos(x)?', 'sin(x)', '-sin(x)', 'cos(x)', 'None of the above', 'A', 'sin(x)'),
    ('MATH201', 'What is the second derivative of x^3?', '6x', '3x^2', '6x^2', '9x', 'A', '6x'),
    ('MATH201', 'What is the integral of 1/x?', 'ln|x|', 'x^2/2', 'x', 'None of the above', 'A', 'ln|x|'),
    ('MATH201', 'What is the Taylor series expansion of e^x?', '1 + x + x^2/2! + x^3/3! + ...', '1 + x + x^2/3! + x^3/4! + ...', '1 + x + x^2 + x^3 + ...', 'None of the above', 'A', '1 + x + x^2/2! + x^3/3! + ...'),
    ('MATH201', 'What is the power rule for derivatives?', 'd/dx(x^n) = n * x^(n-1)', 'd/dx(x^n) = x^(n-1)', 'd/dx(x^n) = n * x^n', 'None of the above', 'A', 'd/dx(x^n) = n * x^(n-1)'),
    ('MATH201', 'What is the derivative of e^x?', 'e^x', 'x^e', 'e', 'None of the above', 'A', 'e^x'),
    ('MATH201', 'What is the integral of x^2?', 'x^3/3', 'x^2/2', '2x^3', 'None of the above', 'A', 'x^3/3'),
    ('MATH201', 'What is the derivative of tan(x)?', 'sec^2(x)', 'sec(x)', 'tan^2(x)', 'None of the above', 'A', 'sec^2(x)'),
    ('MATH201', 'What is the integral of sec^2(x)?', 'tan(x)', 'sec(x)', 'x', 'None of the above', 'A', 'tan(x)'),
    ('MATH201', 'What is the chain rule used for?', 'To differentiate composite functions', 'To integrate composite functions', 'To solve for limits', 'To find the area under curves', 'A', 'To differentiate composite functions'),
    ('MATH201', 'What is the derivative of ln(x)?', '1/x', 'x', 'ln(x)', 'x^(-1)', 'A', '1/x'),
    ('MATH201', 'What is the second derivative of x^4?', '12x^2', '4x^3', '24x^2', '16x^3', 'C', '24x^2'),
    ('MATH201', 'What is the integral of e^x?', 'e^x + C', 'x^e + C', 'e^x', 'None of the above', 'A', 'e^x + C'),
    ('MATH201', 'What is the derivative of x^n?', 'nx^(n-1)', 'nx^n', 'x^n', 'None of the above', 'A', 'nx^(n-1)'),
    ('MATH201', 'What is the derivative of the product of two functions?', 'Product rule', 'Sum rule', 'Quotient rule', 'Chain rule', 'A', 'Product rule'),
    ('MATH201', 'What is the integral of tan(x)?', '-ln|cos(x)|', 'ln|cos(x)|', '-ln|sin(x)|', 'ln|sin(x)|', 'A', '-ln|cos(x)|'),
    ('MATH201', 'What is a critical point in calculus?', 'Where the derivative is zero or undefined', 'Where the function is continuous', 'Where the function reaches its maximum value', 'Where the second derivative is zero', 'A', 'Where the derivative is zero or undefined'),
    ('MATH201', 'What is the second derivative test used for?', 'To classify critical points as minima, maxima, or points of inflection', 'To find the integral of a function', 'To solve for limits', 'To determine continuity of a function', 'A', 'To classify critical points as minima, maxima, or points of inflection'),
    ('MATH201', 'What is the method for finding the area under a curve?', 'Integration', 'Differentiation', 'Limits', 'Product rule', 'A', 'Integration'),
    ('MATH201', 'What is the derivative of cos(x)?', '-sin(x)', 'sin(x)', '-cos(x)', 'None of the above', 'A', '-sin(x)'),
    ('MATH201', 'What is the integral of x^n, n≠-1?', 'x^(n+1)/(n+1)', 'x^n/(n-1)', 'n*x^(n-1)', 'None of the above', 'A', 'x^(n+1)/(n+1)'),
    ('MATH201', 'What is the slope of the tangent line to the curve y = x^2 at x = 3?', '6', '3', '9', '5', 'A', '6'),
    ('MATH201', 'What is the derivative of 1/x?', '-1/x^2', '1/x^2', 'x^2', '-x', 'A', '-1/x^2'),
    ('MATH201', 'What is the integral of sin(x)?', '-cos(x)', 'cos(x)', 'sin(x)', 'None of the above', 'A', '-cos(x)'),
    ('MATH201', 'What is the definition of a limit?', 'The value a function approaches as the input approaches a certain value', 'The value a function reaches at a specific point', 'The derivative of a function', 'The maximum value of a function', 'A', 'The value a function approaches as the input approaches a certain value'),
    ('MATH201', 'What is a function’s domain?', 'The set of all possible input values', 'The set of all possible output values', 'The set of critical points', 'The set of all minimum points', 'A', 'The set of all possible input values'),
]
# cbt_take_exam.py

questions_data = [
    ('MATH201', 'What is the mean value theorem?', 'There exists at least one point where the derivative of a function is equal to the average rate of change', 'The function must be continuous at all points', 'The function must have no maxima', 'None of the above', 'A', 'There exists at least one point where the derivative of a function is equal to the average rate of change'),
    ('MATH201', 'What is the integral of 1/x^2?', '-1/x', 'ln(x)', 'x^(-2)', 'None of the above', 'A', '-1/x'),
    ('MATH201', 'What is the derivative of x^3 + x^2?', '3x^2 + 2x', '3x^3 + 2x^2', 'x^3 + x^2', 'None of the above', 'A', '3x^2 + 2x'),
    ('MATH201', 'What does the second derivative of a function tell us?', 'The concavity of the function', 'The maximum value of the function', 'The average rate of change', 'The slope of the function', 'A', 'The concavity of the function'),
    ('MATH201', 'What is the integral of sec^2(x)?', 'tan(x)', 'sec(x)', 'x', 'None of the above', 'A', 'tan(x)')
    # Add more questions here as needed...
]

def get_filtered_questions(all_questions, course_code):
    return [q for q in all_questions if q[0] == course_code]
       